# Default values for mlflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

MLFlow:
  artifacts:
    bucketName: rook-ceph-rgw-my-store.rook-ceph.svc/mlflow-d7ddbc49-1d71-4826-a93f-0d3993a8ac8d

replicaCount: 1

image:
  repository: evk02/mlflow
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

services:
  postgres:
    enabled: false
    externalURI:
  minio:
    enabled: false
    externalURI:
s3:
  url: rook-ceph-rgw-my-store.rook-ceph.svc/mlflow-d7ddbc49-1d71-4826-a93f-0d3993a8ac8d
  secret: mlflow-bucket

postgresql:
  enabled: true
  auth:
    postgresPassword: leftfoot1
    username: mlflow
    password: leftfoot1
    database: mlflow

minio:
  enabled: false
  auth:
    rootPassword: leftfoot1


oauth2Proxy:
  enabled: false
  repository: "bitnami/oauth2-proxy"
  tag: "7.4.0"

  ## Name of Kubernetes secret holding
  ##   cookie_secret
  ##   client_secret
  secret:

  ## This should match the client ID for your provider
  clientID:
  provider: "keycloak-oidc"

  emailDomains: "*"

  # List of groups
  allowedGroups:
  
  cookieRefresh: "5m"
  keycloak:
    # restrict logins to users with this role (may be given multiple times). Only works with the keycloak-oidc provider.
    allowed_roles:

  oidc:
    # the OpenID Connect issuer URL, e.g. "https://accounts.google.com"
    oidc_issuer_url:

    # OIDC JWKS URI for token verification; required if OIDC discovery is disabled
    oidc_jwks_url:

    # which OIDC claim contains the user's email?
    oidc_email_claim:

    # which OIDC claim contains the user groups?
    oidc_groups_claim:


serviceAccount:
  # Specifies whether a service account should be created
  create:  true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: mlflow.coffea.casa
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
